### ISSUE TITLE
Accelstepper library used?

### ISSUE THREAD

**Issue by ubergeekseven** [JamesMcClelland/esp8266-mqtt-blinds#1]
I see you have step.h included but, were you planning on using the accelstepper library? I need acceleration in my project and planning on being mine on yours. I was wondering how you got around the watchdog issue when combining mqtt with accelstepper. Did you write your own step library instead? 
I am planning on two steppers in two locations with a raspi camera setup, 3d scanner for photogrammetry, and thought that using the raspi as a server and for taking photos based on commands from two wemos devices running mqtt and steppers on each. Relay the position once arrived and then the pi takes a photo. Maybe acceleration isn't needed and I can use your code with some modifications for the setup.

**Comment by JamesMcClelland** [comment]
I need to update the docs for this project, but I didn't use a stepper motor in the end for my project, as the stepper motor that I would need to provide the torque required would have been very large.

I opted to use a DC motor with a reduction gearbox and a rotary encoder instead. When moving the motor I found that calling `yield();` would stop the watchdog from killing the process, but I've heard people have mixed results
